// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: api/proto/flightrecorder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStream_StreamEvents_FullMethodName = "/flightrecorder.EventStream/StreamEvents"
)

// EventStreamClient is the client API for EventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventStream service — agents stream events to the coordinator.
type EventStreamClient interface {
	// StreamEvents is a client-streaming RPC. The agent opens a stream and
	// continuously sends events to the coordinator.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventMessage, StreamAck], error)
}

type eventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamClient(cc grpc.ClientConnInterface) EventStreamClient {
	return &eventStreamClient{cc}
}

func (c *eventStreamClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventMessage, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStream_ServiceDesc.Streams[0], EventStream_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventMessage, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamEventsClient = grpc.ClientStreamingClient[EventMessage, StreamAck]

// EventStreamServer is the server API for EventStream service.
// All implementations must embed UnimplementedEventStreamServer
// for forward compatibility.
//
// EventStream service — agents stream events to the coordinator.
type EventStreamServer interface {
	// StreamEvents is a client-streaming RPC. The agent opens a stream and
	// continuously sends events to the coordinator.
	StreamEvents(grpc.ClientStreamingServer[EventMessage, StreamAck]) error
	mustEmbedUnimplementedEventStreamServer()
}

// UnimplementedEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServer struct{}

func (UnimplementedEventStreamServer) StreamEvents(grpc.ClientStreamingServer[EventMessage, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventStreamServer) mustEmbedUnimplementedEventStreamServer() {}
func (UnimplementedEventStreamServer) testEmbeddedByValue()                     {}

// UnsafeEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServer will
// result in compilation errors.
type UnsafeEventStreamServer interface {
	mustEmbedUnimplementedEventStreamServer()
}

func RegisterEventStreamServer(s grpc.ServiceRegistrar, srv EventStreamServer) {
	// If the following call panics, it indicates UnimplementedEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStream_ServiceDesc, srv)
}

func _EventStream_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventStreamServer).StreamEvents(&grpc.GenericServerStream[EventMessage, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamEventsServer = grpc.ClientStreamingServer[EventMessage, StreamAck]

// EventStream_ServiceDesc is the grpc.ServiceDesc for EventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flightrecorder.EventStream",
	HandlerType: (*EventStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventStream_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/flightrecorder.proto",
}

const (
	AnomalyReport_GetReport_FullMethodName = "/flightrecorder.AnomalyReport/GetReport"
)

// AnomalyReportClient is the client API for AnomalyReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnomalyReport service — clients query the coordinator for reports.
type AnomalyReportClient interface {
	// GetReport returns the latest anomaly report for the given time window.
	GetReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type anomalyReportClient struct {
	cc grpc.ClientConnInterface
}

func NewAnomalyReportClient(cc grpc.ClientConnInterface) AnomalyReportClient {
	return &anomalyReportClient{cc}
}

func (c *anomalyReportClient) GetReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, AnomalyReport_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnomalyReportServer is the server API for AnomalyReport service.
// All implementations must embed UnimplementedAnomalyReportServer
// for forward compatibility.
//
// AnomalyReport service — clients query the coordinator for reports.
type AnomalyReportServer interface {
	// GetReport returns the latest anomaly report for the given time window.
	GetReport(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedAnomalyReportServer()
}

// UnimplementedAnomalyReportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnomalyReportServer struct{}

func (UnimplementedAnomalyReportServer) GetReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedAnomalyReportServer) mustEmbedUnimplementedAnomalyReportServer() {}
func (UnimplementedAnomalyReportServer) testEmbeddedByValue()                       {}

// UnsafeAnomalyReportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnomalyReportServer will
// result in compilation errors.
type UnsafeAnomalyReportServer interface {
	mustEmbedUnimplementedAnomalyReportServer()
}

func RegisterAnomalyReportServer(s grpc.ServiceRegistrar, srv AnomalyReportServer) {
	// If the following call panics, it indicates UnimplementedAnomalyReportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnomalyReport_ServiceDesc, srv)
}

func _AnomalyReport_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyReportServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyReport_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyReportServer).GetReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnomalyReport_ServiceDesc is the grpc.ServiceDesc for AnomalyReport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnomalyReport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flightrecorder.AnomalyReport",
	HandlerType: (*AnomalyReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReport",
			Handler:    _AnomalyReport_GetReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/flightrecorder.proto",
}
