// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/proto/flightrecorder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventMessage wraps all event types in a oneof for transmission.
type EventMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Rank        uint32                 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	NodeId      string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GpuUuid     string                 `protobuf:"bytes,4,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventMessage_GpuMetric
	//	*EventMessage_NcclCollective
	//	*EventMessage_PcieBandwidth
	//	*EventMessage_Nvlink
	//	*EventMessage_Thermal
	Event         isEventMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessage) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *EventMessage) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *EventMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventMessage) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

func (x *EventMessage) GetEvent() isEventMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventMessage) GetGpuMetric() *GPUMetric {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_GpuMetric); ok {
			return x.GpuMetric
		}
	}
	return nil
}

func (x *EventMessage) GetNcclCollective() *NCCLCollective {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_NcclCollective); ok {
			return x.NcclCollective
		}
	}
	return nil
}

func (x *EventMessage) GetPcieBandwidth() *PCIeBandwidth {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_PcieBandwidth); ok {
			return x.PcieBandwidth
		}
	}
	return nil
}

func (x *EventMessage) GetNvlink() *NVLink {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_Nvlink); ok {
			return x.Nvlink
		}
	}
	return nil
}

func (x *EventMessage) GetThermal() *Thermal {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_Thermal); ok {
			return x.Thermal
		}
	}
	return nil
}

type isEventMessage_Event interface {
	isEventMessage_Event()
}

type EventMessage_GpuMetric struct {
	GpuMetric *GPUMetric `protobuf:"bytes,10,opt,name=gpu_metric,json=gpuMetric,proto3,oneof"`
}

type EventMessage_NcclCollective struct {
	NcclCollective *NCCLCollective `protobuf:"bytes,11,opt,name=nccl_collective,json=ncclCollective,proto3,oneof"`
}

type EventMessage_PcieBandwidth struct {
	PcieBandwidth *PCIeBandwidth `protobuf:"bytes,12,opt,name=pcie_bandwidth,json=pcieBandwidth,proto3,oneof"`
}

type EventMessage_Nvlink struct {
	Nvlink *NVLink `protobuf:"bytes,13,opt,name=nvlink,proto3,oneof"`
}

type EventMessage_Thermal struct {
	Thermal *Thermal `protobuf:"bytes,14,opt,name=thermal,proto3,oneof"`
}

func (*EventMessage_GpuMetric) isEventMessage_Event() {}

func (*EventMessage_NcclCollective) isEventMessage_Event() {}

func (*EventMessage_PcieBandwidth) isEventMessage_Event() {}

func (*EventMessage_Nvlink) isEventMessage_Event() {}

func (*EventMessage_Thermal) isEventMessage_Event() {}

type GPUMetric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemperatureC    float64                `protobuf:"fixed64,1,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	PowerWatts      float64                `protobuf:"fixed64,2,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	UtilizationPct  float64                `protobuf:"fixed64,3,opt,name=utilization_pct,json=utilizationPct,proto3" json:"utilization_pct,omitempty"`
	MemBandwidthPct float64                `protobuf:"fixed64,4,opt,name=mem_bandwidth_pct,json=memBandwidthPct,proto3" json:"mem_bandwidth_pct,omitempty"`
	EccErrorsSbe    uint64                 `protobuf:"varint,5,opt,name=ecc_errors_sbe,json=eccErrorsSbe,proto3" json:"ecc_errors_sbe,omitempty"`
	EccErrorsDbe    uint64                 `protobuf:"varint,6,opt,name=ecc_errors_dbe,json=eccErrorsDbe,proto3" json:"ecc_errors_dbe,omitempty"`
	SmClockMhz      float64                `protobuf:"fixed64,7,opt,name=sm_clock_mhz,json=smClockMhz,proto3" json:"sm_clock_mhz,omitempty"`
	ThrottleReasons uint64                 `protobuf:"varint,8,opt,name=throttle_reasons,json=throttleReasons,proto3" json:"throttle_reasons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GPUMetric) Reset() {
	*x = GPUMetric{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetric) ProtoMessage() {}

func (x *GPUMetric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetric.ProtoReflect.Descriptor instead.
func (*GPUMetric) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{1}
}

func (x *GPUMetric) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GPUMetric) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *GPUMetric) GetUtilizationPct() float64 {
	if x != nil {
		return x.UtilizationPct
	}
	return 0
}

func (x *GPUMetric) GetMemBandwidthPct() float64 {
	if x != nil {
		return x.MemBandwidthPct
	}
	return 0
}

func (x *GPUMetric) GetEccErrorsSbe() uint64 {
	if x != nil {
		return x.EccErrorsSbe
	}
	return 0
}

func (x *GPUMetric) GetEccErrorsDbe() uint64 {
	if x != nil {
		return x.EccErrorsDbe
	}
	return 0
}

func (x *GPUMetric) GetSmClockMhz() float64 {
	if x != nil {
		return x.SmClockMhz
	}
	return 0
}

func (x *GPUMetric) GetThrottleReasons() uint64 {
	if x != nil {
		return x.ThrottleReasons
	}
	return 0
}

type NCCLCollective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PgId          string                 `protobuf:"bytes,5,opt,name=pg_id,json=pgId,proto3" json:"pg_id,omitempty"`
	SeqId         uint64                 `protobuf:"varint,6,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Step          int64                  `protobuf:"varint,7,opt,name=step,proto3" json:"step,omitempty"`
	OpType        string                 `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	DataSize      uint64                 `protobuf:"varint,2,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	DurationNs    int64                  `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NCCLCollective) Reset() {
	*x = NCCLCollective{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NCCLCollective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NCCLCollective) ProtoMessage() {}

func (x *NCCLCollective) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NCCLCollective.ProtoReflect.Descriptor instead.
func (*NCCLCollective) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{2}
}

func (x *NCCLCollective) GetPgId() string {
	if x != nil {
		return x.PgId
	}
	return ""
}

func (x *NCCLCollective) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *NCCLCollective) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *NCCLCollective) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *NCCLCollective) GetDataSize() uint64 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *NCCLCollective) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *NCCLCollective) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type PCIeBandwidth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadBwMbs     float64                `protobuf:"fixed64,1,opt,name=read_bw_mbs,json=readBwMbs,proto3" json:"read_bw_mbs,omitempty"`
	WriteBwMbs    float64                `protobuf:"fixed64,2,opt,name=write_bw_mbs,json=writeBwMbs,proto3" json:"write_bw_mbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCIeBandwidth) Reset() {
	*x = PCIeBandwidth{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCIeBandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCIeBandwidth) ProtoMessage() {}

func (x *PCIeBandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCIeBandwidth.ProtoReflect.Descriptor instead.
func (*PCIeBandwidth) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{3}
}

func (x *PCIeBandwidth) GetReadBwMbs() float64 {
	if x != nil {
		return x.ReadBwMbs
	}
	return 0
}

func (x *PCIeBandwidth) GetWriteBwMbs() float64 {
	if x != nil {
		return x.WriteBwMbs
	}
	return 0
}

type NVLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        uint32                 `protobuf:"varint,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	ThroughputGbs float64                `protobuf:"fixed64,2,opt,name=throughput_gbs,json=throughputGbs,proto3" json:"throughput_gbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVLink) Reset() {
	*x = NVLink{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVLink) ProtoMessage() {}

func (x *NVLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVLink.ProtoReflect.Descriptor instead.
func (*NVLink) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{4}
}

func (x *NVLink) GetLinkId() uint32 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *NVLink) GetThroughputGbs() float64 {
	if x != nil {
		return x.ThroughputGbs
	}
	return 0
}

type Thermal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TemperatureC   float64                `protobuf:"fixed64,1,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	ThrottleActive bool                   `protobuf:"varint,2,opt,name=throttle_active,json=throttleActive,proto3" json:"throttle_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Thermal) Reset() {
	*x = Thermal{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thermal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thermal) ProtoMessage() {}

func (x *Thermal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thermal.ProtoReflect.Descriptor instead.
func (*Thermal) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{5}
}

func (x *Thermal) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *Thermal) GetThrottleActive() bool {
	if x != nil {
		return x.ThrottleActive
	}
	return false
}

type StreamAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventsReceived uint64                 `protobuf:"varint,1,opt,name=events_received,json=eventsReceived,proto3" json:"events_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{6}
}

func (x *StreamAck) GetEventsReceived() uint64 {
	if x != nil {
		return x.EventsReceived
	}
	return 0
}

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How far back to look for anomalies (nanoseconds).
	WindowNs      int64 `protobuf:"varint,1,opt,name=window_ns,json=windowNs,proto3" json:"window_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{7}
}

func (x *ReportRequest) GetWindowNs() int64 {
	if x != nil {
		return x.WindowNs
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anomalies     []*AnomalyDetail       `protobuf:"bytes,1,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetAnomalies() []*AnomalyDetail {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

type AnomalyDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DetectedAtNs       int64                  `protobuf:"varint,1,opt,name=detected_at_ns,json=detectedAtNs,proto3" json:"detected_at_ns,omitempty"`
	StragglerRank      uint32                 `protobuf:"varint,2,opt,name=straggler_rank,json=stragglerRank,proto3" json:"straggler_rank,omitempty"`
	OpType             string                 `protobuf:"bytes,3,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	LagNs              int64                  `protobuf:"varint,5,opt,name=lag_ns,json=lagNs,proto3" json:"lag_ns,omitempty"` // median excess lag over peers in flagged blocks (same field number as before)
	DeviationSigma     float64                `protobuf:"fixed64,6,opt,name=deviation_sigma,json=deviationSigma,proto3" json:"deviation_sigma,omitempty"`
	AttributionSummary string                 `protobuf:"bytes,7,opt,name=attribution_summary,json=attributionSummary,proto3" json:"attribution_summary,omitempty"`
	Hits               int64                  `protobuf:"varint,9,opt,name=hits,proto3" json:"hits,omitempty"`
	Groups             int64                  `protobuf:"varint,10,opt,name=groups,proto3" json:"groups,omitempty"`
	CausalChain        []*CausalLink          `protobuf:"bytes,8,rep,name=causal_chain,json=causalChain,proto3" json:"causal_chain,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnomalyDetail) Reset() {
	*x = AnomalyDetail{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyDetail) ProtoMessage() {}

func (x *AnomalyDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyDetail.ProtoReflect.Descriptor instead.
func (*AnomalyDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{9}
}

func (x *AnomalyDetail) GetDetectedAtNs() int64 {
	if x != nil {
		return x.DetectedAtNs
	}
	return 0
}

func (x *AnomalyDetail) GetStragglerRank() uint32 {
	if x != nil {
		return x.StragglerRank
	}
	return 0
}

func (x *AnomalyDetail) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *AnomalyDetail) GetLagNs() int64 {
	if x != nil {
		return x.LagNs
	}
	return 0
}

func (x *AnomalyDetail) GetDeviationSigma() float64 {
	if x != nil {
		return x.DeviationSigma
	}
	return 0
}

func (x *AnomalyDetail) GetAttributionSummary() string {
	if x != nil {
		return x.AttributionSummary
	}
	return ""
}

func (x *AnomalyDetail) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *AnomalyDetail) GetGroups() int64 {
	if x != nil {
		return x.Groups
	}
	return 0
}

func (x *AnomalyDetail) GetCausalChain() []*CausalLink {
	if x != nil {
		return x.CausalChain
	}
	return nil
}

type CausalLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cause         string                 `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CausalLink) Reset() {
	*x = CausalLink{}
	mi := &file_api_proto_flightrecorder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalLink) ProtoMessage() {}

func (x *CausalLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flightrecorder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalLink.ProtoReflect.Descriptor instead.
func (*CausalLink) Descriptor() ([]byte, []int) {
	return file_api_proto_flightrecorder_proto_rawDescGZIP(), []int{10}
}

func (x *CausalLink) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CausalLink) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CausalLink) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_api_proto_flightrecorder_proto protoreflect.FileDescriptor

const file_api_proto_flightrecorder_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/flightrecorder.proto\x12\x0eflightrecorder\"\xb8\x03\n" +
	"\fEventMessage\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\rR\x04rank\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bgpu_uuid\x18\x04 \x01(\tR\agpuUuid\x12:\n" +
	"\n" +
	"gpu_metric\x18\n" +
	" \x01(\v2\x19.flightrecorder.GPUMetricH\x00R\tgpuMetric\x12I\n" +
	"\x0fnccl_collective\x18\v \x01(\v2\x1e.flightrecorder.NCCLCollectiveH\x00R\x0encclCollective\x12F\n" +
	"\x0epcie_bandwidth\x18\f \x01(\v2\x1d.flightrecorder.PCIeBandwidthH\x00R\rpcieBandwidth\x120\n" +
	"\x06nvlink\x18\r \x01(\v2\x16.flightrecorder.NVLinkH\x00R\x06nvlink\x123\n" +
	"\athermal\x18\x0e \x01(\v2\x17.flightrecorder.ThermalH\x00R\athermalB\a\n" +
	"\x05event\"\xbf\x02\n" +
	"\tGPUMetric\x12#\n" +
	"\rtemperature_c\x18\x01 \x01(\x01R\ftemperatureC\x12\x1f\n" +
	"\vpower_watts\x18\x02 \x01(\x01R\n" +
	"powerWatts\x12'\n" +
	"\x0futilization_pct\x18\x03 \x01(\x01R\x0eutilizationPct\x12*\n" +
	"\x11mem_bandwidth_pct\x18\x04 \x01(\x01R\x0fmemBandwidthPct\x12$\n" +
	"\x0eecc_errors_sbe\x18\x05 \x01(\x04R\feccErrorsSbe\x12$\n" +
	"\x0eecc_errors_dbe\x18\x06 \x01(\x04R\feccErrorsDbe\x12 \n" +
	"\fsm_clock_mhz\x18\a \x01(\x01R\n" +
	"smClockMhz\x12)\n" +
	"\x10throttle_reasons\x18\b \x01(\x04R\x0fthrottleReasons\"\xc5\x01\n" +
	"\x0eNCCLCollective\x12\x13\n" +
	"\x05pg_id\x18\x05 \x01(\tR\x04pgId\x12\x15\n" +
	"\x06seq_id\x18\x06 \x01(\x04R\x05seqId\x12\x12\n" +
	"\x04step\x18\a \x01(\x03R\x04step\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12\x1b\n" +
	"\tdata_size\x18\x02 \x01(\x04R\bdataSize\x12\x1f\n" +
	"\vduration_ns\x18\x03 \x01(\x03R\n" +
	"durationNs\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"Q\n" +
	"\rPCIeBandwidth\x12\x1e\n" +
	"\vread_bw_mbs\x18\x01 \x01(\x01R\treadBwMbs\x12 \n" +
	"\fwrite_bw_mbs\x18\x02 \x01(\x01R\n" +
	"writeBwMbs\"H\n" +
	"\x06NVLink\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\rR\x06linkId\x12%\n" +
	"\x0ethroughput_gbs\x18\x02 \x01(\x01R\rthroughputGbs\"W\n" +
	"\aThermal\x12#\n" +
	"\rtemperature_c\x18\x01 \x01(\x01R\ftemperatureC\x12'\n" +
	"\x0fthrottle_active\x18\x02 \x01(\bR\x0ethrottleActive\"4\n" +
	"\tStreamAck\x12'\n" +
	"\x0fevents_received\x18\x01 \x01(\x04R\x0eeventsReceived\",\n" +
	"\rReportRequest\x12\x1b\n" +
	"\twindow_ns\x18\x01 \x01(\x03R\bwindowNs\"M\n" +
	"\x0eReportResponse\x12;\n" +
	"\tanomalies\x18\x01 \x03(\v2\x1d.flightrecorder.AnomalyDetailR\tanomalies\"\xd7\x02\n" +
	"\rAnomalyDetail\x12$\n" +
	"\x0edetected_at_ns\x18\x01 \x01(\x03R\fdetectedAtNs\x12%\n" +
	"\x0estraggler_rank\x18\x02 \x01(\rR\rstragglerRank\x12\x17\n" +
	"\aop_type\x18\x03 \x01(\tR\x06opType\x12\x15\n" +
	"\x06lag_ns\x18\x05 \x01(\x03R\x05lagNs\x12'\n" +
	"\x0fdeviation_sigma\x18\x06 \x01(\x01R\x0edeviationSigma\x12/\n" +
	"\x13attribution_summary\x18\a \x01(\tR\x12attributionSummary\x12\x12\n" +
	"\x04hits\x18\t \x01(\x03R\x04hits\x12\x16\n" +
	"\x06groups\x18\n" +
	" \x01(\x03R\x06groups\x12=\n" +
	"\fcausal_chain\x18\b \x03(\v2\x1a.flightrecorder.CausalLinkR\vcausalChainJ\x04\b\x04\x10\x05\"Z\n" +
	"\n" +
	"CausalLink\x12\x14\n" +
	"\x05cause\x18\x01 \x01(\tR\x05cause\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2X\n" +
	"\vEventStream\x12I\n" +
	"\fStreamEvents\x12\x1c.flightrecorder.EventMessage\x1a\x19.flightrecorder.StreamAck(\x012[\n" +
	"\rAnomalyReport\x12J\n" +
	"\tGetReport\x12\x1d.flightrecorder.ReportRequest\x1a\x1e.flightrecorder.ReportResponseBJZHgithub.com/RyanJHamby/distributed-gpu-training-flight-recorder/api/protob\x06proto3"

var (
	file_api_proto_flightrecorder_proto_rawDescOnce sync.Once
	file_api_proto_flightrecorder_proto_rawDescData []byte
)

func file_api_proto_flightrecorder_proto_rawDescGZIP() []byte {
	file_api_proto_flightrecorder_proto_rawDescOnce.Do(func() {
		file_api_proto_flightrecorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_flightrecorder_proto_rawDesc), len(file_api_proto_flightrecorder_proto_rawDesc)))
	})
	return file_api_proto_flightrecorder_proto_rawDescData
}

var file_api_proto_flightrecorder_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_flightrecorder_proto_goTypes = []any{
	(*EventMessage)(nil),   // 0: flightrecorder.EventMessage
	(*GPUMetric)(nil),      // 1: flightrecorder.GPUMetric
	(*NCCLCollective)(nil), // 2: flightrecorder.NCCLCollective
	(*PCIeBandwidth)(nil),  // 3: flightrecorder.PCIeBandwidth
	(*NVLink)(nil),         // 4: flightrecorder.NVLink
	(*Thermal)(nil),        // 5: flightrecorder.Thermal
	(*StreamAck)(nil),      // 6: flightrecorder.StreamAck
	(*ReportRequest)(nil),  // 7: flightrecorder.ReportRequest
	(*ReportResponse)(nil), // 8: flightrecorder.ReportResponse
	(*AnomalyDetail)(nil),  // 9: flightrecorder.AnomalyDetail
	(*CausalLink)(nil),     // 10: flightrecorder.CausalLink
}
var file_api_proto_flightrecorder_proto_depIdxs = []int32{
	1,  // 0: flightrecorder.EventMessage.gpu_metric:type_name -> flightrecorder.GPUMetric
	2,  // 1: flightrecorder.EventMessage.nccl_collective:type_name -> flightrecorder.NCCLCollective
	3,  // 2: flightrecorder.EventMessage.pcie_bandwidth:type_name -> flightrecorder.PCIeBandwidth
	4,  // 3: flightrecorder.EventMessage.nvlink:type_name -> flightrecorder.NVLink
	5,  // 4: flightrecorder.EventMessage.thermal:type_name -> flightrecorder.Thermal
	9,  // 5: flightrecorder.ReportResponse.anomalies:type_name -> flightrecorder.AnomalyDetail
	10, // 6: flightrecorder.AnomalyDetail.causal_chain:type_name -> flightrecorder.CausalLink
	0,  // 7: flightrecorder.EventStream.StreamEvents:input_type -> flightrecorder.EventMessage
	7,  // 8: flightrecorder.AnomalyReport.GetReport:input_type -> flightrecorder.ReportRequest
	6,  // 9: flightrecorder.EventStream.StreamEvents:output_type -> flightrecorder.StreamAck
	8,  // 10: flightrecorder.AnomalyReport.GetReport:output_type -> flightrecorder.ReportResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_flightrecorder_proto_init() }
func file_api_proto_flightrecorder_proto_init() {
	if File_api_proto_flightrecorder_proto != nil {
		return
	}
	file_api_proto_flightrecorder_proto_msgTypes[0].OneofWrappers = []any{
		(*EventMessage_GpuMetric)(nil),
		(*EventMessage_NcclCollective)(nil),
		(*EventMessage_PcieBandwidth)(nil),
		(*EventMessage_Nvlink)(nil),
		(*EventMessage_Thermal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_flightrecorder_proto_rawDesc), len(file_api_proto_flightrecorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_flightrecorder_proto_goTypes,
		DependencyIndexes: file_api_proto_flightrecorder_proto_depIdxs,
		MessageInfos:      file_api_proto_flightrecorder_proto_msgTypes,
	}.Build()
	File_api_proto_flightrecorder_proto = out.File
	file_api_proto_flightrecorder_proto_goTypes = nil
	file_api_proto_flightrecorder_proto_depIdxs = nil
}
